//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace atomic.rss.wp7.AuthentificationService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.QueryResultOfUser))]
    public partial class QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfUser", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.ChangeSetEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.User>))]
    public partial class QueryResultOfUser : atomic.rss.wp7.AuthentificationService.QueryResult {
        
        private System.Collections.ObjectModel.ObservableCollection<object> IncludedResultsField;
        
        private System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.User> RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<object> IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.User> RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainServiceFault", Namespace="DomainServices")]
    public partial class DomainServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool IsDomainExceptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo> OperationErrorsField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDomainException {
            get {
                return this.IsDomainExceptionField;
            }
            set {
                if ((this.IsDomainExceptionField.Equals(value) != true)) {
                    this.IsDomainExceptionField = value;
                    this.RaisePropertyChanged("IsDomainException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo> OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultInfo", Namespace="DomainServices")]
    public partial class ValidationResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNamesField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNames {
            get {
                return this.SourceMemberNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceMemberNamesField, value) != true)) {
                    this.SourceMemberNamesField = value;
                    this.RaisePropertyChanged("SourceMemberNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeSetEntry", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.QueryResultOfUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wp7.AuthentificationService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.User>))]
    public partial class ChangeSetEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> AssociationsField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ConflictMembersField;
        
        private object EntityField;
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>> EntityActionsField;
        
        private bool HasMemberChangesField;
        
        private int IdField;
        
        private bool IsDeleteConflictField;
        
        private atomic.rss.wp7.AuthentificationService.DomainOperation OperationField;
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> OriginalAssociationsField;
        
        private object OriginalEntityField;
        
        private object StoreEntityField;
        
        private System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo> ValidationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> Associations {
            get {
                return this.AssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssociationsField, value) != true)) {
                    this.AssociationsField = value;
                    this.RaisePropertyChanged("Associations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<string> ConflictMembers {
            get {
                return this.ConflictMembersField;
            }
            set {
                if ((object.ReferenceEquals(this.ConflictMembersField, value) != true)) {
                    this.ConflictMembersField = value;
                    this.RaisePropertyChanged("ConflictMembers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>> EntityActions {
            get {
                return this.EntityActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityActionsField, value) != true)) {
                    this.EntityActionsField = value;
                    this.RaisePropertyChanged("EntityActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMemberChanges {
            get {
                return this.HasMemberChangesField;
            }
            set {
                if ((this.HasMemberChangesField.Equals(value) != true)) {
                    this.HasMemberChangesField = value;
                    this.RaisePropertyChanged("HasMemberChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsDeleteConflict {
            get {
                return this.IsDeleteConflictField;
            }
            set {
                if ((this.IsDeleteConflictField.Equals(value) != true)) {
                    this.IsDeleteConflictField = value;
                    this.RaisePropertyChanged("IsDeleteConflict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public atomic.rss.wp7.AuthentificationService.DomainOperation Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> OriginalAssociations {
            get {
                return this.OriginalAssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalAssociationsField, value) != true)) {
                    this.OriginalAssociationsField = value;
                    this.RaisePropertyChanged("OriginalAssociations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object OriginalEntity {
            get {
                return this.OriginalEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalEntityField, value) != true)) {
                    this.OriginalEntityField = value;
                    this.RaisePropertyChanged("OriginalEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object StoreEntity {
            get {
                return this.StoreEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreEntityField, value) != true)) {
                    this.StoreEntityField = value;
                    this.RaisePropertyChanged("StoreEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ValidationResultInfo> ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainOperation", Namespace="DomainServices")]
    public enum DomainOperation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Query = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoke = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/atomic.rss.Web.Services")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> RolesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthentificationService.AuthentificationDomainServiceSoap")]
    public interface AuthentificationDomainServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AuthentificationDomainServiceSoap/Login", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/LoginDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginLogin(string userName, string password, bool isPersistent, string customData, System.AsyncCallback callback, object asyncState);
        
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AuthentificationDomainServiceSoap/Logout", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/LogoutDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState);
        
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndLogout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AuthentificationDomainServiceSoap/GetUser", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/GetUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginGetUser(System.AsyncCallback callback, object asyncState);
        
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndGetUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChanges", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wp7.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChangesDomainServiceFa" +
            "ult", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> EndSubmitChanges(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthentificationDomainServiceSoapChannel : atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public atomic.rss.wp7.AuthentificationService.QueryResultOfUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public atomic.rss.wp7.AuthentificationService.QueryResultOfUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public atomic.rss.wp7.AuthentificationService.QueryResultOfUser Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthentificationDomainServiceSoapClient : System.ServiceModel.ClientBase<atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap>, atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogoutDelegate;
        
        private EndOperationDelegate onEndLogoutDelegate;
        
        private System.Threading.SendOrPostCallback onLogoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserDelegate;
        
        private EndOperationDelegate onEndGetUserDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitChangesDelegate;
        
        private EndOperationDelegate onEndSubmitChangesDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitChangesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AuthentificationDomainServiceSoapClient() {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationDomainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<LogoutCompletedEventArgs> LogoutCompleted;
        
        public event System.EventHandler<GetUserCompletedEventArgs> GetUserCompleted;
        
        public event System.EventHandler<SubmitChangesCompletedEventArgs> SubmitChangesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.BeginLogin(string userName, string password, bool isPersistent, string customData, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(userName, password, isPersistent, customData, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string userName = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            bool isPersistent = ((bool)(inValues[2]));
            string customData = ((string)(inValues[3]));
            return ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).BeginLogin(userName, password, isPersistent, customData, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            atomic.rss.wp7.AuthentificationService.QueryResultOfUser retVal = ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string userName, string password, bool isPersistent, string customData) {
            this.LoginAsync(userName, password, isPersistent, customData, null);
        }
        
        public void LoginAsync(string userName, string password, bool isPersistent, string customData, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        userName,
                        password,
                        isPersistent,
                        customData}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.BeginLogout(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogout(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.EndLogout(System.IAsyncResult result) {
            return base.Channel.EndLogout(result);
        }
        
        private System.IAsyncResult OnBeginLogout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).BeginLogout(callback, asyncState);
        }
        
        private object[] OnEndLogout(System.IAsyncResult result) {
            atomic.rss.wp7.AuthentificationService.QueryResultOfUser retVal = ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).EndLogout(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogoutCompleted(object state) {
            if ((this.LogoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogoutAsync() {
            this.LogoutAsync(null);
        }
        
        public void LogoutAsync(object userState) {
            if ((this.onBeginLogoutDelegate == null)) {
                this.onBeginLogoutDelegate = new BeginOperationDelegate(this.OnBeginLogout);
            }
            if ((this.onEndLogoutDelegate == null)) {
                this.onEndLogoutDelegate = new EndOperationDelegate(this.OnEndLogout);
            }
            if ((this.onLogoutCompletedDelegate == null)) {
                this.onLogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoutCompleted);
            }
            base.InvokeAsync(this.onBeginLogoutDelegate, null, this.onEndLogoutDelegate, this.onLogoutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.BeginGetUser(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUser(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        atomic.rss.wp7.AuthentificationService.QueryResultOfUser atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.EndGetUser(System.IAsyncResult result) {
            return base.Channel.EndGetUser(result);
        }
        
        private System.IAsyncResult OnBeginGetUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).BeginGetUser(callback, asyncState);
        }
        
        private object[] OnEndGetUser(System.IAsyncResult result) {
            atomic.rss.wp7.AuthentificationService.QueryResultOfUser retVal = ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).EndGetUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserCompleted(object state) {
            if ((this.GetUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserAsync() {
            this.GetUserAsync(null);
        }
        
        public void GetUserAsync(object userState) {
            if ((this.onBeginGetUserDelegate == null)) {
                this.onBeginGetUserDelegate = new BeginOperationDelegate(this.OnBeginGetUser);
            }
            if ((this.onEndGetUserDelegate == null)) {
                this.onEndGetUserDelegate = new EndOperationDelegate(this.OnEndGetUser);
            }
            if ((this.onGetUserCompletedDelegate == null)) {
                this.onGetUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserDelegate, null, this.onEndGetUserDelegate, this.onGetUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitChanges(changeSet, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap.EndSubmitChanges(System.IAsyncResult result) {
            return base.Channel.EndSubmitChanges(result);
        }
        
        private System.IAsyncResult OnBeginSubmitChanges(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet = ((System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry>)(inValues[0]));
            return ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).BeginSubmitChanges(changeSet, callback, asyncState);
        }
        
        private object[] OnEndSubmitChanges(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> retVal = ((atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap)(this)).EndSubmitChanges(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitChangesCompleted(object state) {
            if ((this.SubmitChangesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitChangesCompleted(this, new SubmitChangesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitChangesAsync(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet) {
            this.SubmitChangesAsync(changeSet, null);
        }
        
        public void SubmitChangesAsync(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet, object userState) {
            if ((this.onBeginSubmitChangesDelegate == null)) {
                this.onBeginSubmitChangesDelegate = new BeginOperationDelegate(this.OnBeginSubmitChanges);
            }
            if ((this.onEndSubmitChangesDelegate == null)) {
                this.onEndSubmitChangesDelegate = new EndOperationDelegate(this.OnEndSubmitChanges);
            }
            if ((this.onSubmitChangesCompletedDelegate == null)) {
                this.onSubmitChangesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitChangesCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitChangesDelegate, new object[] {
                        changeSet}, this.onEndSubmitChangesDelegate, this.onSubmitChangesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap CreateChannel() {
            return new AuthentificationDomainServiceSoapClientChannel(this);
        }
        
        private class AuthentificationDomainServiceSoapClientChannel : ChannelBase<atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap>, atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap {
            
            public AuthentificationDomainServiceSoapClientChannel(System.ServiceModel.ClientBase<atomic.rss.wp7.AuthentificationService.AuthentificationDomainServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string userName, string password, bool isPersistent, string customData, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = userName;
                _args[1] = password;
                _args[2] = isPersistent;
                _args[3] = customData;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                atomic.rss.wp7.AuthentificationService.QueryResultOfUser _result = ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogout(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Logout", _args, callback, asyncState);
                return _result;
            }
            
            public atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndLogout(System.IAsyncResult result) {
                object[] _args = new object[0];
                atomic.rss.wp7.AuthentificationService.QueryResultOfUser _result = ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(base.EndInvoke("Logout", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUser(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetUser", _args, callback, asyncState);
                return _result;
            }
            
            public atomic.rss.wp7.AuthentificationService.QueryResultOfUser EndGetUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                atomic.rss.wp7.AuthentificationService.QueryResultOfUser _result = ((atomic.rss.wp7.AuthentificationService.QueryResultOfUser)(base.EndInvoke("GetUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = changeSet;
                System.IAsyncResult _result = base.BeginInvoke("SubmitChanges", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> EndSubmitChanges(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry> _result = ((System.Collections.ObjectModel.ObservableCollection<atomic.rss.wp7.AuthentificationService.ChangeSetEntry>)(base.EndInvoke("SubmitChanges", _args, result)));
                return _result;
            }
        }
    }
}
