//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atomic.rss.outlook.FeedsManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/atomic.rss.Web.Models")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedsManager.IFeedsManager")]
    public interface IFeedsManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/LoadArticles", ReplyAction="http://tempuri.org/IFeedsManager/LoadArticlesResponse")]
        void LoadArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/AddChannels", ReplyAction="http://tempuri.org/IFeedsManager/AddChannelsResponse")]
        void AddChannels(string user, string channels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/RemoveChannelsFromUser", ReplyAction="http://tempuri.org/IFeedsManager/RemoveChannelsFromUserResponse")]
        void RemoveChannelsFromUser(string user, int id_channels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/SetArticlesReadForUser", ReplyAction="http://tempuri.org/IFeedsManager/SetArticlesReadForUserResponse")]
        void SetArticlesReadForUser(int id_article, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/SetAllArticlesReadForUser", ReplyAction="http://tempuri.org/IFeedsManager/SetAllArticlesReadForUserResponse")]
        void SetAllArticlesReadForUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/GetUserChannels", ReplyAction="http://tempuri.org/IFeedsManager/GetUserChannelsResponse")]
        atomic.rss.outlook.FeedsManager.Item[] GetUserChannels(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/GetChannelsWithoutUser", ReplyAction="http://tempuri.org/IFeedsManager/GetChannelsWithoutUserResponse")]
        atomic.rss.outlook.FeedsManager.Item[] GetChannelsWithoutUser(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/GetArticlesUnread", ReplyAction="http://tempuri.org/IFeedsManager/GetArticlesUnreadResponse")]
        atomic.rss.outlook.FeedsManager.Item[] GetArticlesUnread(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/GetArticlesReaded", ReplyAction="http://tempuri.org/IFeedsManager/GetArticlesReadedResponse")]
        atomic.rss.outlook.FeedsManager.Item[] GetArticlesReaded(string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/DestroyChannelsRelation", ReplyAction="http://tempuri.org/IFeedsManager/DestroyChannelsRelationResponse")]
        void DestroyChannelsRelation(int id_channels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/DestroyChannelsRelationWithUser", ReplyAction="http://tempuri.org/IFeedsManager/DestroyChannelsRelationWithUserResponse")]
        void DestroyChannelsRelationWithUser(int id_user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/DestroyArticlesRelation", ReplyAction="http://tempuri.org/IFeedsManager/DestroyArticlesRelationResponse")]
        void DestroyArticlesRelation(int id_channels);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedsManager/DestroyArticlesRelationWithUser", ReplyAction="http://tempuri.org/IFeedsManager/DestroyArticlesRelationWithUserResponse")]
        void DestroyArticlesRelationWithUser(int id_user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeedsManagerChannel : atomic.rss.outlook.FeedsManager.IFeedsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedsManagerClient : System.ServiceModel.ClientBase<atomic.rss.outlook.FeedsManager.IFeedsManager>, atomic.rss.outlook.FeedsManager.IFeedsManager {
        
        public FeedsManagerClient() {
        }
        
        public FeedsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LoadArticles() {
            base.Channel.LoadArticles();
        }
        
        public void AddChannels(string user, string channels) {
            base.Channel.AddChannels(user, channels);
        }
        
        public void RemoveChannelsFromUser(string user, int id_channels) {
            base.Channel.RemoveChannelsFromUser(user, id_channels);
        }
        
        public void SetArticlesReadForUser(int id_article, string user) {
            base.Channel.SetArticlesReadForUser(id_article, user);
        }
        
        public void SetAllArticlesReadForUser(string user) {
            base.Channel.SetAllArticlesReadForUser(user);
        }
        
        public atomic.rss.outlook.FeedsManager.Item[] GetUserChannels(string user) {
            return base.Channel.GetUserChannels(user);
        }
        
        public atomic.rss.outlook.FeedsManager.Item[] GetChannelsWithoutUser(string user) {
            return base.Channel.GetChannelsWithoutUser(user);
        }
        
        public atomic.rss.outlook.FeedsManager.Item[] GetArticlesUnread(string user) {
            return base.Channel.GetArticlesUnread(user);
        }
        
        public atomic.rss.outlook.FeedsManager.Item[] GetArticlesReaded(string user) {
            return base.Channel.GetArticlesReaded(user);
        }
        
        public void DestroyChannelsRelation(int id_channels) {
            base.Channel.DestroyChannelsRelation(id_channels);
        }
        
        public void DestroyChannelsRelationWithUser(int id_user) {
            base.Channel.DestroyChannelsRelationWithUser(id_user);
        }
        
        public void DestroyArticlesRelation(int id_channels) {
            base.Channel.DestroyArticlesRelation(id_channels);
        }
        
        public void DestroyArticlesRelationWithUser(int id_user) {
            base.Channel.DestroyArticlesRelationWithUser(id_user);
        }
    }
}
