//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace atomic.rss.wpf.AuthentificationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="DomainServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.QueryResultOfUser))]
    public partial class QueryResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfUser", Namespace="DomainServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ValidationResultInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ChangeSetEntry[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ChangeSetEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.User[]))]
    public partial class QueryResultOfUser : atomic.rss.wpf.AuthentificationService.QueryResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] IncludedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private atomic.rss.wpf.AuthentificationService.User[] RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object[] IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public atomic.rss.wpf.AuthentificationService.User[] RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainServiceFault", Namespace="DomainServices")]
    [System.SerializableAttribute()]
    public partial class DomainServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDomainExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private atomic.rss.wpf.AuthentificationService.ValidationResultInfo[] OperationErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDomainException {
            get {
                return this.IsDomainExceptionField;
            }
            set {
                if ((this.IsDomainExceptionField.Equals(value) != true)) {
                    this.IsDomainExceptionField = value;
                    this.RaisePropertyChanged("IsDomainException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public atomic.rss.wpf.AuthentificationService.ValidationResultInfo[] OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultInfo", Namespace="DomainServices")]
    [System.SerializableAttribute()]
    public partial class ValidationResultInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SourceMemberNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] SourceMemberNames {
            get {
                return this.SourceMemberNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceMemberNamesField, value) != true)) {
                    this.SourceMemberNamesField = value;
                    this.RaisePropertyChanged("SourceMemberNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeSetEntry", Namespace="DomainServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.QueryResultOfUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ValidationResultInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.ChangeSetEntry[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, int[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(int[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object[]>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(atomic.rss.wpf.AuthentificationService.User[]))]
    public partial class ChangeSetEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int[]> AssociationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ConflictMembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object EntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object[]> EntityActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasMemberChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeleteConflictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private atomic.rss.wpf.AuthentificationService.DomainOperation OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, int[]> OriginalAssociationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object OriginalEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object StoreEntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private atomic.rss.wpf.AuthentificationService.ValidationResultInfo[] ValidationErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, int[]> Associations {
            get {
                return this.AssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssociationsField, value) != true)) {
                    this.AssociationsField = value;
                    this.RaisePropertyChanged("Associations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] ConflictMembers {
            get {
                return this.ConflictMembersField;
            }
            set {
                if ((object.ReferenceEquals(this.ConflictMembersField, value) != true)) {
                    this.ConflictMembersField = value;
                    this.RaisePropertyChanged("ConflictMembers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object[]> EntityActions {
            get {
                return this.EntityActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityActionsField, value) != true)) {
                    this.EntityActionsField = value;
                    this.RaisePropertyChanged("EntityActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMemberChanges {
            get {
                return this.HasMemberChangesField;
            }
            set {
                if ((this.HasMemberChangesField.Equals(value) != true)) {
                    this.HasMemberChangesField = value;
                    this.RaisePropertyChanged("HasMemberChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsDeleteConflict {
            get {
                return this.IsDeleteConflictField;
            }
            set {
                if ((this.IsDeleteConflictField.Equals(value) != true)) {
                    this.IsDeleteConflictField = value;
                    this.RaisePropertyChanged("IsDeleteConflict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public atomic.rss.wpf.AuthentificationService.DomainOperation Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, int[]> OriginalAssociations {
            get {
                return this.OriginalAssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalAssociationsField, value) != true)) {
                    this.OriginalAssociationsField = value;
                    this.RaisePropertyChanged("OriginalAssociations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object OriginalEntity {
            get {
                return this.OriginalEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalEntityField, value) != true)) {
                    this.OriginalEntityField = value;
                    this.RaisePropertyChanged("OriginalEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object StoreEntity {
            get {
                return this.StoreEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreEntityField, value) != true)) {
                    this.StoreEntityField = value;
                    this.RaisePropertyChanged("StoreEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public atomic.rss.wpf.AuthentificationService.ValidationResultInfo[] ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainOperation", Namespace="DomainServices")]
    public enum DomainOperation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Query = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoke = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/atomic.rss.Web.Services")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] RolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthentificationService.AuthentificationDomainServiceSoap")]
    public interface AuthentificationDomainServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthentificationDomainServiceSoap/Login", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/LoginDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        atomic.rss.wpf.AuthentificationService.QueryResultOfUser Login(string userName, string password, bool isPersistent, string customData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthentificationDomainServiceSoap/Logout", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/LogoutDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        atomic.rss.wpf.AuthentificationService.QueryResultOfUser Logout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthentificationDomainServiceSoap/GetUser", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/GetUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/GetUserDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        atomic.rss.wpf.AuthentificationService.QueryResultOfUser GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChanges", ReplyAction="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(atomic.rss.wpf.AuthentificationService.DomainServiceFault), Action="http://tempuri.org/AuthentificationDomainServiceSoap/SubmitChangesDomainServiceFa" +
            "ult", Name="DomainServiceFault", Namespace="DomainServices")]
        atomic.rss.wpf.AuthentificationService.ChangeSetEntry[] SubmitChanges(atomic.rss.wpf.AuthentificationService.ChangeSetEntry[] changeSet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthentificationDomainServiceSoapChannel : atomic.rss.wpf.AuthentificationService.AuthentificationDomainServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthentificationDomainServiceSoapClient : System.ServiceModel.ClientBase<atomic.rss.wpf.AuthentificationService.AuthentificationDomainServiceSoap>, atomic.rss.wpf.AuthentificationService.AuthentificationDomainServiceSoap {
        
        public AuthentificationDomainServiceSoapClient() {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationDomainServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationDomainServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public atomic.rss.wpf.AuthentificationService.QueryResultOfUser Login(string userName, string password, bool isPersistent, string customData) {
            return base.Channel.Login(userName, password, isPersistent, customData);
        }
        
        public atomic.rss.wpf.AuthentificationService.QueryResultOfUser Logout() {
            return base.Channel.Logout();
        }
        
        public atomic.rss.wpf.AuthentificationService.QueryResultOfUser GetUser() {
            return base.Channel.GetUser();
        }
        
        public atomic.rss.wpf.AuthentificationService.ChangeSetEntry[] SubmitChanges(atomic.rss.wpf.AuthentificationService.ChangeSetEntry[] changeSet) {
            return base.Channel.SubmitChanges(changeSet);
        }
    }
}
